version: '3.8'

services:
  db_promotion:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    hostname: db_promotion
    environment:
      - POSTGRES_USER=fastapi_promotion
      - POSTGRES_PASSWORD=fastapi_promotion
      - POSTGRES_DB=fastapi_promotion

  web:
    build:
      dockerfile: Dockerfile
    command: uvicorn src.promotion.main:app --reload --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - db_promotion


volumes:
  postgres_data: